"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-05 08:47:06.132235

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'archived', name='todo_status'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('recurrence_unit', sa.Enum('day', 'week', 'month', name='recurrence_unit'), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('recurrence_series_id', sa.UUID(), nullable=True),
    sa.Column('recurrence_anchor_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmet_dependency_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(recurrence_unit IS NULL AND recurrence_interval IS NULL) OR (recurrence_unit IS NOT NULL AND recurrence_interval >= 1)', name='ck_todos_recurrence_complete'),
    sa.CheckConstraint('priority IN (10, 20, 30)', name='ck_todos_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todos_live_blocked', 'todos', ['unmet_dependency_count'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_live_due', 'todos', ['due_date', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_live_name', 'todos', ['name', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_live_priority', 'todos', ['priority', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_live_status', 'todos', ['status', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_todos_series', 'todos', ['recurrence_series_id'], unique=False)
    op.create_table('todo_dependencies',
    sa.Column('todo_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('todo_id <> depends_on_id', name='ck_no_self_dependency'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['todos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('todo_id', 'depends_on_id')
    )
    op.create_index('ix_dependencies_depends_on', 'todo_dependencies', ['depends_on_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dependencies_depends_on', table_name='todo_dependencies')
    op.drop_table('todo_dependencies')
    op.drop_index('ix_todos_series', table_name='todos')
    op.drop_index('ix_todos_live_status', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_todos_live_priority', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_todos_live_name', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_todos_live_due', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_todos_live_blocked', table_name='todos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('todos')
    # ### end Alembic commands ###
    # Hand-added: autogenerate creates native enum types implicitly as part of
    # create_table (via CREATE TYPE ... AS ENUM) but drop_table does NOT drop
    # them back, since a type could in principle be shared by other tables.
    # Without this, a downgrade-then-upgrade cycle fails with
    # `DuplicateObjectError: type "todo_status" already exists`.
    sa.Enum(name='todo_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recurrence_unit').drop(op.get_bind(), checkfirst=True)
